apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "niord-proxy.fullname" . }}
  labels:
    {{- include "niord-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "niord-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "niord-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "niord-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EXECUTION_MODE
              value: {{ default "test" .Values.executionMode | quote }}
            - name: NIORD_PROXY_SERVER
              value: {{ default "https://niord.e-navigation.net" .Values.server | quote }}
            - name: NIORD_PROXY_AREAS
              value: {{ default "" .Values.areas | quote }}
            - name: NIORD_REPO_PATH
              value: {{ default "" .Values.repoPath | quote }}
            - name: NIORD_REPO_TYPE
              value: {{ default "" .Values.repoType | quote }}
            - name: NIORD_PROXY_TRACKING_ID
              value: {{ default "" .Values.trackingID | quote }}
            - name: NIORD_PROXY_WMS_URL
              value: {{ default "" .Values.wmsUrl | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
